services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.25
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/todoapp
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: password
      LIQUIBASE_COMMAND_CHANGELOG_FILE: db.changelog-master.yaml
    volumes:
      - ./database/liquibase/changelogs:/liquibase/changelog
    profiles:
      - migration
    command: ["update"]

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/todoapp
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    environment:
      API_BASE_URL: http://backend:8000
    ports:
      - "8501:8501"
      - "5679:5679"  # Debug port
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: streamlit run app.py --server.address 0.0.0.0 --server.port 8501

volumes:
  postgres_data: